name: EnderGuard
version: 1.0
main: com.cebelian.serverstats.ServerStatsPlugin
api-version: 1.20
description: Exportálja a szerver adatait MongoDB-be.
commands:
  getid:
    description: Kiírja a szerver azonosítóját.
    usage: /getid
