name: Java CI with Maven

on:
  push:
    tags:
      - 'v*.*.*'   # Akkor indul el, ha kiadsz egy release-t v1.0.0, v1.2.3 stb.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: enderguard
        path: target/*.jar
