name: Java CI with Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java code
      run: |
        mkdir out
        find src/main/java -name "*.java" > sources.txt
        javac -d out @sources.txt

    - name: Package JAR
      run: |
        jar cfm enderguard.jar src/main/resources/plugin.yml -C out .
        mkdir build
        mv enderguard.jar build/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/enderguard.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
